// Mock data for the application
export const mockNotices = [
    {
        _id: "1",
        title: "Annual Sports Day",
        content:
            "Annual Sports Day will be held on March 15th, 2024. All students must participate.",
        category: "event",
        author: { name: "John Smith" },
        createdAt: "2024-03-01T10:00:00Z",
    },
    {
        _id: "2",
        title: "Parent-Teacher Meeting",
        content: "Parent-Teacher meeting scheduled for March 20th, 2024.",
        category: "announcement",
        author: { name: "Mary Johnson" },
        createdAt: "2024-03-02T09:00:00Z",
    },
    {
        _id: "3",
        title: "Science Fair",
        content: "The annual Science Fair will take place on April 10th, 2024.",
        category: "event",
        author: { name: "Jane Doe" },
        createdAt: "2024-03-05T11:00:00Z",
    },
    {
        _id: "4",
        title: "School Trip",
        content:
            "A school trip to the museum is scheduled for April 25th, 2024.",
        category: "event",
        author: { name: "James Brown" },
        createdAt: "2024-03-08T12:00:00Z",
    },
    {
        _id: "5",
        title: "Book Fair",
        content: "The school's Book Fair will be held on May 5th, 2024.",
        category: "event",
        author: { name: "Emily White" },
        createdAt: "2024-03-10T13:00:00Z",
    },
    {
        _id: "6",
        title: "Exam Schedule",
        content: "The final exam schedule has been released for June 2024.",
        category: "announcement",
        author: { name: "Michael Green" },
        createdAt: "2024-03-12T14:00:00Z",
    },
    {
        _id: "7",
        title: "Summer Camp",
        content: "Summer Camp registration is open for July 2024.",
        category: "event",
        author: { name: "Laura Black" },
        createdAt: "2024-03-15T15:00:00Z",
    },
    {
        _id: "8",
        title: "Art Exhibition",
        content:
            "The annual Art Exhibition will take place on August 15th, 2024.",
        category: "event",
        author: { name: "David Grey" },
        createdAt: "2024-03-18T16:00:00Z",
    },
    {
        _id: "9",
        title: "Teacher's Day",
        content: "Teacher's Day will be celebrated on September 5th, 2024.",
        category: "event",
        author: { name: "Helen Blue" },
        createdAt: "2024-03-20T17:00:00Z",
    },
    {
        _id: "10",
        title: "Music Concert",
        content:
            "The school's Music Concert is scheduled for October 10th, 2024.",
        category: "event",
        author: { name: "Chris Red" },
        createdAt: "2024-03-22T18:00:00Z",
    },
    {
        _id: "11",
        title: "Halloween Party",
        content: "Join us for a spooky Halloween Party on October 31st, 2024.",
        category: "event",
        author: { name: "Anna Yellow" },
        createdAt: "2024-03-25T19:00:00Z",
    },
    {
        _id: "12",
        title: "Thanksgiving Feast",
        content: "Celebrate Thanksgiving with us on November 28th, 2024.",
        category: "event",
        author: { name: "Richard Orange" },
        createdAt: "2024-03-27T20:00:00Z",
    },
    {
        _id: "13",
        title: "Winter Break",
        content: "Winter Break will start from December 20th, 2024.",
        category: "announcement",
        author: { name: "Nancy Pink" },
        createdAt: "2024-03-30T21:00:00Z",
    },
    {
        _id: "14",
        title: "New Year's Celebration",
        content: "Ring in the New Year with us on January 1st, 2025.",
        category: "event",
        author: { name: "Tom Violet" },
        createdAt: "2024-04-02T22:00:00Z",
    },
    {
        _id: "15",
        title: "Math Olympiad",
        content: "The Math Olympiad will be held on February 10th, 2025.",
        category: "event",
        author: { name: "Samantha Indigo" },
        createdAt: "2024-04-05T23:00:00Z",
    },
    {
        _id: "16",
        title: "Drama Performance",
        content: "Don't miss the Drama Performance on March 5th, 2025.",
        category: "event",
        author: { name: "Kevin Turquoise" },
        createdAt: "2024-04-07T24:00:00Z",
    },
    {
        _id: "17",
        title: "Cultural Fest",
        content: "Join us for a vibrant Cultural Fest on April 20th, 2025.",
        category: "event",
        author: { name: "Laura Magenta" },
        createdAt: "2024-04-10T25:00:00Z",
    },
    {
        _id: "18",
        title: "Sports Meet",
        content: "The Sports Meet will be held on May 10th, 2025.",
        category: "event",
        author: { name: "Daniel Cyan" },
        createdAt: "2024-04-12T26:00:00Z",
    },
    {
        _id: "19",
        title: "Graduation Ceremony",
        content: "Celebrate our graduates on June 15th, 2025.",
        category: "event",
        author: { name: "Alice Coral" },
        createdAt: "2024-04-15T27:00:00Z",
    },
    {
        _id: "20",
        title: "Alumni Reunion",
        content: "Alumni Reunion is scheduled for July 5th, 2025.",
        category: "event",
        author: { name: "Paul Lavender" },
        createdAt: "2024-04-17T28:00:00Z",
    },
];

export const mockResults = [
    {
        _id: "1",
        exam: "Mid Term",
        class: "10",
        year: 2024,
        subjects: [
            { name: "Mathematics", marks: 85, grade: "A" },
            { name: "Science", marks: 90, grade: "A+" },
            { name: "English", marks: 88, grade: "A" },
        ],
        totalMarks: 263,
        percentage: 87.67,
        grade: "A",
        createdAt: "2024-02-15T08:00:00Z",
    },
    {
        _id: "2",
        exam: "Mid Term",
        class: "10",
        year: 2024,
        subjects: [
            { name: "Mathematics", marks: 78, grade: "B+" },
            { name: "Science", marks: 85, grade: "A" },
            { name: "English", marks: 82, grade: "A" },
        ],
        totalMarks: 245,
        percentage: 81.67,
        grade: "A",
        createdAt: "2024-02-15T08:00:00Z",
    },
    {
        _id: "3",
        exam: "Mid Term",
        class: "10",
        year: 2024,
        subjects: [
            { name: "Mathematics", marks: 92, grade: "A+" },
            { name: "Science", marks: 88, grade: "A" },
            { name: "English", marks: 80, grade: "A" },
        ],
        totalMarks: 260,
        percentage: 86.67,
        grade: "A",
        createdAt: "2024-02-15T08:00:00Z",
    },
    {
        _id: "4",
        exam: "Mid Term",
        class: "10",
        year: 2024,
        subjects: [
            { name: "Mathematics", marks: 81, grade: "A" },
            { name: "Science", marks: 87, grade: "A" },
            { name: "English", marks: 84, grade: "A" },
        ],
        totalMarks: 252,
        percentage: 84,
        grade: "A",
        createdAt: "2024-02-15T08:00:00Z",
    },
    {
        _id: "5",
        exam: "Mid Term",
        class: "10",
        year: 2024,
        subjects: [
            { name: "Mathematics", marks: 89, grade: "A" },
            { name: "Science", marks: 91, grade: "A+" },
            { name: "English", marks: 85, grade: "A" },
        ],
        totalMarks: 265,
        percentage: 88.33,
        grade: "A",
        createdAt: "2024-02-15T08:00:00Z",
    },
    {
        _id: "6",
        exam: "Mid Term",
        class: "10",
        year: 2024,
        subjects: [
            { name: "Mathematics", marks: 76, grade: "B+" },
            { name: "Science", marks: 82, grade: "A" },
            { name: "English", marks: 79, grade: "B+" },
        ],
        totalMarks: 237,
        percentage: 79,
        grade: "B+",
        createdAt: "2024-02-15T08:00:00Z",
    },
    {
        _id: "7",
        exam: "Mid Term",
        class: "10",
        year: 2024,
        subjects: [
            { name: "Mathematics", marks: 84, grade: "A" },
            { name: "Science", marks: 89, grade: "A+" },
            { name: "English", marks: 83, grade: "A" },
        ],
        totalMarks: 256,
        percentage: 85.33,
        grade: "A",
        createdAt: "2024-02-15T08:00:00Z",
    },
    {
        _id: "8",
        exam: "Mid Term",
        class: "10",
        year: 2024,
        subjects: [
            { name: "Mathematics", marks: 90, grade: "A+" },
            { name: "Science", marks: 93, grade: "A+" },
            { name: "English", marks: 87, grade: "A" },
        ],
        totalMarks: 270,
        percentage: 90,
        grade: "A+",
        createdAt: "2024-02-15T08:00:00Z",
    },
    {
        _id: "9",
        exam: "Mid Term",
        class: "10",
        year: 2024,
        subjects: [
            { name: "Mathematics", marks: 79, grade: "B+" },
            { name: "Science", marks: 80, grade: "A" },
            { name: "English", marks: 78, grade: "B+" },
        ],
        totalMarks: 237,
        percentage: 79,
        grade: "B+",
        createdAt: "2024-02-15T08:00:00Z",
    },
    {
        _id: "10",
        exam: "Mid Term",
        class: "10",
        year: 2024,
        subjects: [
            { name: "Mathematics", marks: 87, grade: "A" },
            { name: "Science", marks: 92, grade: "A+" },
            { name: "English", marks: 86, grade: "A" },
        ],
        totalMarks: 265,
        percentage: 88.33,
        grade: "A",
        createdAt: "2024-02-15T08:00:00Z",
    },
];

export const mockTeachers = [
    {
        _id: "1",
        name: "Md Akhtaruzzaman",
        position: "Assistant Teacher Business Studies",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "2",
        name: "Md Nazrul Islam Shah",
        position: "Headmaster",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "3",
        name: "Mst. Anowara Begum",
        position: "Assistant Headmaster",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "4",
        name: "Uttam Kuamr Debnath",
        position: "Teacher Hindu Religion And Moral Education",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "5",
        name: "Md Jahangir Alam",
        position: "Assistant Teacher Library And Information Science",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "6",
        name: "Noor Jahan",
        position: "Teacher Islam Religion And Moral Education",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "7",
        name: "Ram Chandra Debnath",
        position: "Assistant Teacher Physical Science",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "8",
        name: "Md. Mostafizur Rahman",
        position: "Assistant Teacher Mathematics, General Science",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "9",
        name: "Mohidul Islam",
        position: "Assistant Teacher Physical Education",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "10",
        name: "Eusuf Ali",
        position: "Teacher Agricultural Science",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "11",
        name: "Md Moslemuddin",
        position: "Teacher",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "12",
        name: "Ferdousi Banu",
        position: "Teacher",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "13",
        name: "S M Shakhawat Hossain",
        position: "Teacher",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "14",
        name: "Parvin Khatun",
        position: "Teacher",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "15",
        name: "Md. Sanowar Hossain",
        position: "Teacher",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
    {
        _id: "16",
        name: "Md Delowar Hossain",
        position: "Teacher",
        image: "https://unsplash.com/photos/a-man-standing-in-front-of-a-purple-wall-bYODySpLIhE",
    },
];

export const mockGalleryImages = [
    {
        id: "1",
        url: "https://www.vecteezy.com/vector-art/455459-students-playing-in-front-of-school",
        title: "Students Playing in Front of School",
        description: "Students playing in front of school",
        date: "2023-01-15",
    },
    {
        id: "2",
        url: "https://lovepik.com/images/png-primary-school-students.html",
        title: "Primary School Students",
        description: "Primary school students in a classroom",
        date: "2023-02-10",
    },
    {
        id: "3",
        url: "https://pnghunter.com/png/students-17/",
        title: "Student's PNG Image",
        description: "A student studying at a desk",
        date: "2023-03-05",
    },
    {
        id: "4",
        url: "https://www.vecteezy.com/vector-art/4120762-school-students",
        title: "School Students",
        description: "Students in school uniform",
        date: "2023-03-25",
    },
    {
        id: "5",
        url: "https://www.freepik.com/free-photos-vectors/school",
        title: "School Event",
        description: "A school event with students",
        date: "2023-04-10",
    },
    {
        id: "6",
        url: "https://www.pikpng.com/pngl/m/67-676715_group-of-students-png-transparent-image-group-of.png",
        title: "Group of Students",
        description: "Group of students gathered together",
        date: "2023-05-20",
    },
    {
        id: "7",
        url: "https://www.vecteezy.com/vector-art/714324-students-in-classroom",
        title: "Students in Classroom",
        description: "Students attentively listening in a classroom",
        date: "2023-06-05",
    },
    {
        id: "8",
        url: "https://pngio.com/PNG/a72656196-high-school-student-transparent-background.html",
        title: "High School Students",
        description: "High school students interacting",
        date: "2023-07-15",
    },
    {
        id: "9",
        url: "https://pixabay.com/vectors/back-to-school-welcome-school-4057884/",
        title: "Back to School",
        description: "Welcome back to school event",
        date: "2023-08-22",
    },
    {
        id: "10",
        url: "https://www.cleanpng.com/png-student-classroom-education-school-children-teache-314832/",
        title: "Classroom Activity",
        description: "Students engaged in a classroom activity",
        date: "2023-09-12",
    },
    {
        id: "11",
        url: "https://www.cleanpng.com/png-student-learning-classroom-education-1476729/",
        title: "Student Learning",
        description: "A student engrossed in learning",
        date: "2023-10-05",
    },
    {
        id: "12",
        url: "https://www.cleanpng.com/png-student-teacher-classroom-education-school-4281360/",
        title: "Teacher and Students",
        description: "Teacher engaging with students in a classroom",
        date: "2023-10-20",
    },
    {
        id: "13",
        url: "https://www.cleanpng.com/png-student-classroom-education-school-children-teache-5681499/",
        title: "Class Discussion",
        description: "Students participating in a class discussion",
        date: "2023-11-15",
    },
    {
        id: "14",
        url: "https://pixabay.com/photos/kids-students-classroom-school-3762152/",
        title: "Students in Uniform",
        description: "Students in uniform outside the school",
        date: "2023-12-01",
    },
    {
        id: "15",
        url: "https://www.pngfind.com/pngs/m/122-1223667_high-school-student-graduation-transparent-high-school-student.png",
        title: "Student Graduation",
        description: "Students celebrating graduation",
        date: "2024-01-10",
    },
    {
        id: "16",
        url: "https://www.pngfind.com/pngs/m/50-506453_happy-students-illustration-png-png-download-students-png.png",
        title: "Happy Students",
        description: "Happy students enjoying their time at school",
        date: "2024-01-25",
    },
    {
        id: "17",
        url: "https://www.pngkey.com/detail/u2w7y3y3q8a9i1t4_student-transparent-students-in-class-png-png-download/",
        title: "Students in Class",
        description: "Students attentively listening to a lesson",
        date: "2024-02-05",
    },
    {
        id: "18",
        url: "https://www.cleanpng.com/png-students-playing-school-children-school-student-png-2676076/",
        title: "Students Playing",
        description: "Students playing during recess",
        date: "2024-02-25",
    },
    {
        id: "19",
        url: "https://www.pngmart.com/image/91579",
        title: "School Assembly",
        description: "Students gathered for a school assembly",
        date: "2024-03-10",
    },
    {
        id: "20",
        url: "https://www.freepik.com/free-vector/students-study-exam-male-female-students-studying-together_10247154.htm",
        title: "Study Session",
        description: "Students studying together for an exam",
        date: "2024-03-25",
    },
    {
        id: "21",
        url: "https://www.cleanpng.com/png-graduation-student-drawing-student-327876/",
        title: "Graduation Day",
        description: "Students celebrating their graduation",
        date: "2024-04-05",
    },
    {
        id: "22",
        url: "https://www.freepik.com/free-vector/group-students-illustration_2997897.htm",
        title: "Group of Students",
        description: "Group of students posing together",
        date: "2024-04-15",
    },
    {
        id: "23",
        url: "https://www.freepik.com/free-vector/back-to-school-background_859021.htm",
        title: "School Fair",
        description: "Students enjoying a school fair",
        date: "2024-05-05",
    },
    {
        id: "24",
        url: "https://www.vecteezy.com/vector-art/142843-school-children",
        title: "School Children",
        description: "School children on a field trip",
        date: "2024-05-20",
    },
    {
        id: "25",
        url: "https://www.freepik.com/free-vector/cartoon-kids-school_1083048.htm",
        title: "School Kids",
        description: "Cartoon of school kids playing",
        date: "2024-06-10",
    },
    {
        id: "26",
        url: "https://www.freepik.com/free-vector/classroom-interior-with-students_788419.htm",
        title: "Classroom Interior",
        description: "Interior view of a classroom with students",
        date: "2024-06-25",
    },
    {
        id: "27",
        url: "https://pixabay.com/vectors/back-to-school-blackboard-board-chalk-4057877/",
        title: "Back to School Blackboard",
        description: "Blackboard with 'Back to School' written on it",
        date: "2024-07-10",
    },
    {
        id: "28",
        url: "https://www.vecteezy.com/vector-art/1069933-students-reading-books",
        title: "Students Reading Books",
        description: "Students reading books in a library",
        date: "2024-07-25",
    },
    {
        id: "29",
        url: "https://www.freepik.com/free-vector/school-children-playing-yard_1120595.htm",
        title: "Playing in the Yard",
        description: "School children playing in the yard",
        date: "2024-08-10",
    },
    {
        id: "30",
        url: "https://pixabay.com/vectors/students-school-classroom-teacher-551473/",
        title: "Classroom Teacher",
        description: "Teacher instructing students in a classroom",
        date: "2024-08-25",
    },
    {
        id: "31",
        url: "https://www.freepik.com/free-vector/students-returning-to-school_1113558.htm",
        title: "Returning to School",
        description: "Students returning to school after a break",
        date: "2024-09-05",
    },
    {
        id: "32",
        url: "https://pixabay.com/vectors/students-learning-studying-books-2816247/",
        title: "Students Learning",
        description: "Students learning with books",
        date: "2024-09-20",
    },
    {
        id: "33",
        url: "https://www.vecteezy.com/vector-art/139232-children-playing-in-school",
        title: "Children Playing",
        description: "Children playing games in the school yard",
        date: "2024-10-10",
    },
    {
        id: "34",
        url: "https://www.cleanpng.com/png-school-student-studying-cartoon-children-2387574/",
        title: "Student Studying",
        description: "A student studying hard",
        date: "2024-10-25",
    },
    {
        id: "35",
        url: "https://www.freepik.com/free-vector/kids-having-fun-school_1099842.htm",
        title: "Kids Having Fun",
        description: "Kids having fun during a school activity",
        date: "2024-11-05",
    },
    {
        id: "36",
        url: "https://www.cleanpng.com/png-students-learning-studying-education-6782328/",
        title: "Group Study",
        description: "Group of students studying together",
        date: "2024-11-20",
    },
    {
        id: "37",
        url: "https://pixabay.com/vectors/classroom-school-teacher-students-1690845/",
        title: "Classroom Environment",
        description: "A typical classroom environment with students",
        date: "2024-12-10",
    },
    {
        id: "38",
        url: "https://www.freepik.com/free-vector/happy-students_809134.htm",
        title: "Happy Students",
        description: "Students smiling and enjoying their time",
        date: "2024-12-25",
    },
    {
        id: "39",
        url: "https://www.vecteezy.com/vector-art/1277185-students-standing-outside-school-building",
        title: "Outside School",
        description: "Students standing outside the school building",
        date: "2025-01-10",
    },
    {
        id: "40",
        url: "https://www.cleanpng.com/png-classroom-students-teacher-school-1291328/",
        title: "Classroom Activity",
        description: "Students engaged in a classroom activity",
        date: "2025-01-25",
    },
    {
        id: "41",
        url: "https://www.freepik.com/free-vector/back-to-school-background-with-students_1095871.htm",
        title: "Back to School Background",
        description: "Students with a 'Back to School' sign",
        date: "2025-02-10",
    },
    {
        id: "42",
        url: "https://pixabay.com/vectors/school-building-students-architecture-1195088/",
        title: "School Building",
        description: "Students outside a school building",
        date: "2025-02-25",
    },
    {
        id: "43",
        url: "https://www.cleanpng.com/png-happy-students-png-image-free-download-6302395/",
        title: "Happy Students PNG",
        description: "Students looking happy and excited",
        date: "2025-03-10",
    },
    {
        id: "44",
        url: "https://pixabay.com/photos/education-know-how-learn-school-3005942/",
        title: "Education and Learning",
        description: "A focus on education and learning",
        date: "2025-03-25",
    },
    {
        id: "45",
        url: "https://www.freepik.com/free-vector/children-studying_1086318.htm",
        title: "Children Studying",
        description: "Children studying together at school",
        date: "2025-04-10",
    },
    {
        id: "46",
        url: "https://www.vecteezy.com/vector-art/142955-back-to-school-students",
        title: "Back to School Students",
        description: "Students with 'Back to School' banners",
        date: "2025-04-25",
    },
    {
        id: "47",
        url: "https://www.freepik.com/free-vector/kids-going-to-school_1093437.htm",
        title: "Kids Going to School",
        description: "Kids walking towards school",
        date: "2025-05-10",
    },
    {
        id: "48",
        url: "https://www.cleanpng.com/png-students-in-the-library-4085219/",
        title: "Students in Library",
        description: "Students reading in the library",
        date: "2025-05-25",
    },
    {
        id: "49",
        url: "https://pixabay.com/photos/kids-students-classroom-school-3762152/",
        title: "Classroom Activity",
        description: "Students engaged in a classroom activity",
        date: "2025-06-10",
    },
    {
        id: "50",
        url: "https://www.freepik.com/free-vector/children-playground-school_1818732.htm",
        title: "Playground at School",
        description: "Children playing on the school playground",
        date: "2025-06-25",  },
];

const mockResult = {
    student: {
        fullName: "John Doe",
        class: "10",
        branch: "Science",
        group: "G", // Class 10 can only have group G
        roll: "2024001",
        academicYear: "2024",
    },
    result: {
        examType: "FINAL",
        academicYear: "2024",
        subjects: [
            {
                subject: "Mathematics",
                achievedMark: 85,
                fullMark: 100,
                grade: "A+",
                teacherComment: "Excellent problem-solving skills",
            },
            {
                subject: "Physics",
                achievedMark: 78,
                fullMark: 100,
                grade: "A",
                teacherComment: "Good theoretical understanding",
            },
            {
                subject: "Chemistry",
                achievedMark: 82,
                fullMark: 100,
                grade: "A+",
                teacherComment: "Strong practical knowledge",
            },
            {
                subject: "Biology",
                achievedMark: 75,
                fullMark: 100,
                grade: "A",
                teacherComment: "Needs more focus on diagrams",
            },
            {
                subject: "English",
                achievedMark: 88,
                fullMark: 100,
                grade: "A+",
                teacherComment: "Excellent communication skills",
            },
        ],
        totalMark: 408,
        gpa: 4.85,
    },
};